In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np 

In [3]:
l = [1,2,3]

In [5]:
type(l)


list

In [7]:
arr = np.array(l) #It converts object , var. into an array . 

In [8]:
arr

array([1, 2, 3])

In [9]:
type(arr) #nd - n Dimensional Array 

numpy.ndarray

In [10]:
print(arr)

[1 2 3]


In [11]:
arr.ndim

1

In [13]:
l2 = [[1,2,3],[1,2,3],[1,2,3]] #2-D Array 

In [14]:
arr = np.array(l2)

In [18]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)



2
(3, 3)
9
int64


In [25]:
#To make Arr of 0's and 1's of any shape , size
zeros = np.zeros((3,5)) #(3,5) is shape .
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
ones = np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
#To generate Random No.s 
import numpy as np 

print(np.random.random()) #Generates no. bw 0 to 1
np.random.random((3,3)) #Generates array of no. bw 0 to 1 

0.087347403868558


array([[0.03737825, 0.00503442, 0.33803315],
       [0.67507886, 0.58870949, 0.50324899],
       [0.59599627, 0.42338016, 0.91111252]])

In [6]:
np.arange(1,10,1) # Start , Stop , Step  

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(1,10,10) #Produces 10 values bw 1 to 10 that are equidistant to each other .

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [16]:
Arr = np.random.random((4,3))

In [17]:
Arr

array([[0.23768602, 0.47054073, 0.57617371],
       [0.29397163, 0.92352894, 0.40755006],
       [0.37923357, 0.02398763, 0.08504728],
       [0.93395422, 0.38476528, 0.61055271]])

In [19]:
Arr = np.reshape( Arr, (3,4)) #To reshape the same Array keeping no. of eles. same
Arr

array([[0.23768602, 0.47054073, 0.57617371, 0.29397163],
       [0.92352894, 0.40755006, 0.37923357, 0.02398763],
       [0.08504728, 0.93395422, 0.38476528, 0.61055271]])

In [20]:
Arr.flatten()


array([0.23768602, 0.47054073, 0.57617371, 0.29397163, 0.92352894,
       0.40755006, 0.37923357, 0.02398763, 0.08504728, 0.93395422,
       0.38476528, 0.61055271])

In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
print(arr+1) # Adds 1 to Every Ele. 
print(arr-1)
print(arr*1)
print(arr/1)
print(arr%1)
print(arr**2)

[2 3 4 5 6 7]
[0 1 2 3 4 5]
[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
[0 0 0 0 0 0]
[ 1  4  9 16 25 36]


In [6]:
arr = arr  + 1
arr


array([2, 3, 4, 5, 6, 7])

In [8]:
print(arr.max())
print(arr.min())

7
2


In [15]:
#If we take Multi-Dim Arr 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
print(arr.max(axis = 0)) #Wewill get Max. Ele. column wise.
print(arr.max(axis = 1)) #We will get Max. ele. column wise.
print(arr.min(axis = 0))# 
print(arr.min(axis = 1))

[7 8 9]
[3 6 9]
[1 2 3]
[1 4 7]


In [17]:
arr.sum()

45

In [20]:
#To perform on Multiple Arrays. 
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [21]:
print(arr1 + arr2) #To Add two Arrs., Must have Same Shape . 
print(arr2 *arr1) 


[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [22]:
arr1.dot(arr2) #Actual Multiplication of two Arrs.

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [23]:
arr2.dot(arr1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [27]:
arr = np.array([1,2,3,4,5]) #1-D Array 
print(arr[:])
print(arr[:1])
print(arr[:2])
print(arr[:3])
print(arr[1:])
print(arr[2:])
print(arr[3:])
print(arr[2:-2])

[1 2 3 4 5]
[1]
[1 2]
[1 2 3]
[2 3 4 5]
[3 4 5]
[4 5]
[3]


In [29]:
#Multi-Dim Array 
print(arr1[:,:]) #Used for Rows , Used for columns 
print(arr1[:,:1])
print(arr1[:1,:])
print(arr1[:,1:2])
print(arr1[1:2,1:2])#To retrieve The mId ele. 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [4]
 [7]]
[[1 2 3]]
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[5]]


In [1]:
#Array Sorting using Numpy Arrays- 
import numpy as np 

In [2]:
arr = np.array([[7,3,8,6,4],[7,2,9,8,6],[5,4,2,3,1]])
arr

array([[7, 3, 8, 6, 4],
       [7, 2, 9, 8, 6],
       [5, 4, 2, 3, 1]])

In [3]:
# We can use np.sort(a,axis=-1,kind=None,order=None)
np.sort(arr, axis = 1 ,kind ='mergesort') #Will sort arr row wise

#You can assign kind = 'mergesort', 'quicksort',etc. 

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [4]:
np.sort(arr, axis = 0  ,kind ='mergesort')

array([[5, 2, 2, 3, 1],
       [7, 3, 8, 6, 4],
       [7, 4, 9, 8, 6]])

In [5]:
np.sort(arr,kind ='mergesort') #By Defaut , axis = 1 i.e. row wise 

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [8]:
#Meging/Concatenating two arrays ; Splitting Arrays - 
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[8,7,6,5],[4,3,2,1]])
 
print(np.vstack((arr1,arr2))) #To stack Vertically 
print(np.hstack((arr1,arr2))) #To stack Horizonatally 

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [12]:
arr = np.concatenate((arr1,arr2),axis = 0) #By Default , axis = 0 
np.concatenate((arr1,arr2),axis = 1)

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [13]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [15]:
print (np.hsplit(arr,2)) # Splits arr into 2 halves horizontally 
print (np.vsplit(arr,2)) # Splits arr into 2 halves vertically 

[array([[1, 2],
       [5, 6],
       [8, 7],
       [4, 3]]), array([[3, 4],
       [7, 8],
       [6, 5],
       [2, 1]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[8, 7, 6, 5],
       [4, 3, 2, 1]])]


In [17]:
#Array Slicing-
arr2 = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [18]:
arr1 = np.array([1,2,3,4,5,6,7,8])
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
arr1[0]

1

In [22]:
arr1[:] #Start Index : End Index 
arr1[:-3] #Will remove last 3 eles. 
arr1[3:] #Will remove first 3 eles.

#For Multi dim 
arr2[ : , : ]
arr2[ :1, : ] #Will print the 1st Row
arr2[ :2, :  ]#Will print first 2 Rows
arr2[1:, : ] #All rows except the 1st Row 
arr2[2 , : ] #Will Print all cols. of 2nd Row 
arr2[1: , 1]
arr2[ 1: ,1:]#All cols. except 1st Col. 
arr2[1: , 1:2] 
arr2[ 1,1 ]

#For cropping - 
arr2[1: , 1: ]

array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])

In [26]:
#Automation using Numpy 

#To print no. of Eles. i.e >5 using List

q=0

lst = [1,2,3,4,5,6,7,8,9,10]
for i in lst:
    if(i>5):
        q+=1
print(q)

5


In [27]:
#To print no. of Eles. i.e >5 using Numpy . 

lst =np.array([1,2,3,4,5,6,7,8,9,10]) 
lst > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [28]:
lst[lst>5]  #Will print the value Jiska index = True hai 

array([ 6,  7,  8,  9, 10])

In [30]:
# /// You can try variety of Constraints 
lst[lst % 3 == 0 ]


array([3, 6, 9])